### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by lloverain** [BE3dARt/ARMA-3-ARTILLERY-CALCULATOR-ARES#2]
Excuse me, how do you extract the altitude from the map? Can you share the experience?

**Comment by BE3dARt** [comment]
I hoped no one would ask, haha. It's a very unsophisticated and dirty solution; however, I don't remember it exactly. In Arma III's scripting language, you can return a height at a certain point. With another command, you can then copy this data to the clipboard. I iterated these two steps over the whole map in a "while"-loop. I wrote a little c++ script to capture all these clipboard strings and store them into a file.

**Comment by lloverain** [comment]
Thank you very much for your answer
