### ISSUE TITLE
MAAWS Implementation Request

### ISSUE THREAD

**Issue by festive-panda** [BE3dARt/ARMA-3-ARTILLERY-CALCULATOR-ARES#3]
Is there any way to get the maws calculator running? Or would you have to re-code the system? I really want to redneck artillery on Koth for shits and gigs. It would be fun. I already love it for the scorcher but the maws would be great.

**Comment by BE3dARt** [comment]
Hello **Festive-Panda**

Thank you for stopping by at my repository!

I tried implementing the MAAWS last time I worked on this project. However, I sadly could not figure out the error in my calculation. I have to admit, it's a long time ago since then and I don't know how fast I will get into it again, since I currently don't play Arma III anymore.

If you have the calculation, adding it to the map is the easy part.

**Comment by BE3dARt** [comment]
I did some research, and I've come to the conclusion that it should indeed be possible to calculate it with an appropriate equation.

The difference to the Sochor/Scorcher calculator is that artillery ammo lacks air friction in Arma III; I need to figure out how to plug it into the current equation.

Initial Speed (config file) = **350 m/s**
Air Friction (config file) = **0.05 ?**

Initial Speed (measured) = 343.441 m/s

**Comment by sheptonomallet** [comment]
W... Maybe you can start by explaining which equation ?

**Comment by sheptonomallet** [comment]
sorry to be a bit snippy 
but...

**Comment by sheptonomallet** [comment]
quite honestly you only get any good science when theres some spice

**Comment by sheptonomallet** [comment]
there's some front end twitter issues

**Comment by sheptonomallet** [comment]
#1 merry christmas
HA
HA
HA
HA
HA

> I did some research, and I've come to the conclusion that it should indeed be possible to calculate it with an appropriate equation.
> 
> The difference to the Sochor/Scorcher calculator is that artillery ammo lacks air friction in Arma III; I need to figure out how to plug it into the current equation.
> 
> Initial Speed (config file) = **350 m/s** Air Friction (config file) = **0.05 ?**
> 
> Initial Speed (measured) = 343.441 m/s

and i kno you've been lonely boy

**Comment by sheptonomallet** [comment]
explain me wot the panda is at ;?)
